# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0jpbd1jnp10f237cpazrh7vm8gnifh4shdnvlq33svhxbpqg325g";
    aarch64-linux = "14cbn55x8ghcvmqxl2zlj7r5iaz0l7v3nrrhcy487jv4ig9qgv1j";
    x86_64-darwin = "02kyl6x5p0grvkkgvja4bhpx2dpp2xcmvnjypjymglbssjbfw18y";
    aarch64-darwin = "1vc7v9x9l9v527pz6rypl2zq50rpmacz304hvllg1h9azdlc8njj";
  };

  urlMap = {
    x86_64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.5/cpctl_0.10.5_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.5/cpctl_0.10.5_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.5/cpctl_0.10.5_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.5/cpctl_0.10.5_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cpctl";
  version = "0.10.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/libexec/cpctl $out/share/cloud-playground $out/bin
    cp -vr ./cpctl $out/libexec/cpctl/cpctl
    cp -vr ./.cpctl.yaml $out/share/cloud-playground/.cpctl.yaml
    cp -vr ./aws-local $out/share/cloud-playground/aws-local
    cp -vr ./kind $out/share/cloud-playground/kind
    cp -vr ./localstack $out/share/cloud-playground/localstack
    cp -vr ./manifests $out/share/cloud-playground/manifests
    cp -vr ./moto $out/share/cloud-playground/moto
    cp -vr ./tofu $out/share/cloud-playground/tofu
    cat > $out/bin/cpctl <<EOF
    #!${stdenvNoCC.shell}
    export CPCTL_ROOT="$out/share/cloud-playground"
    exec "$out/libexec/cpctl/cpctl" "\$@"
    EOF
    chmod +x $out/bin/cpctl
  '';

  meta = {
    description = "Cloud Playground CLI for AWS and Kubernetes";
    homepage = "https://github.com/afeldman/cloud-playground";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
