# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "07l9g9fs10jnpv6fgap6x8gxf6ymrzxjfk6vscf7afyylnw1v1p2";
    aarch64-linux = "0l4inn3w18ar7vhpkn96vnxikzfyb82r85979a1payjn3z5cgvsk";
    x86_64-darwin = "0hwfazpsyskd083s4rahrmsaf7npp5nvm2aj17p8mgyvsgy22567";
    aarch64-darwin = "1gphdyz29kb96c7fa70c8gcq8ld9jfl0xn6d8hg170clk66w4syx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.6/cpctl_0.10.6_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.6/cpctl_0.10.6_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.6/cpctl_0.10.6_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.6/cpctl_0.10.6_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cpctl";
  version = "0.10.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/libexec/cpctl $out/share/cloud-playground $out/bin
    cp -vr ./cpctl $out/libexec/cpctl/cpctl
    cp -vr ./.cpctl.yaml $out/share/cloud-playground/.cpctl.yaml
    cp -vr ./aws-local $out/share/cloud-playground/aws-local
    cp -vr ./kind $out/share/cloud-playground/kind
    cp -vr ./localstack $out/share/cloud-playground/localstack
    cp -vr ./manifests $out/share/cloud-playground/manifests
    cp -vr ./moto $out/share/cloud-playground/moto
    cp -vr ./tofu $out/share/cloud-playground/tofu
    cat > $out/bin/cpctl <<'EOF'
    #!${stdenvNoCC.shell}
    self_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
    prefix="$(CDPATH= cd -- "$self_dir/.." && pwd)"
    export CPCTL_ROOT="$prefix/share/cloud-playground"
    exec "$prefix/libexec/cpctl/cpctl" "$@"
    EOF
    chmod +x $out/bin/cpctl
  '';

  meta = {
    description = "Cloud Playground CLI for AWS and Kubernetes";
    homepage = "https://github.com/afeldman/cloud-playground";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
