# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "128alnswfbkms3hrv2lp0jq80l3jmn562zq40k7w19f4s1l5ms1c";
    aarch64-linux = "056d18yc85asrf85d8jpb7nli4l343ccp2qyj0xkrlgm7i4aph6g";
    x86_64-darwin = "1cdjw3km1sv1cijwqdzcmsvy4k92lmr34zg630iq3h1jvvzjkl10";
    aarch64-darwin = "0qkw0qzf0h2x75x44la2qngdw51driyfhv2xsb0hkb07ij72008w";
  };

  urlMap = {
    x86_64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.9/cpctl_0.10.9_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.9/cpctl_0.10.9_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.9/cpctl_0.10.9_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/afeldman/cloud-playground/releases/download/v0.10.9/cpctl_0.10.9_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cpctl";
  version = "0.10.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/libexec/cpctl $out/share/cloud-playground $out/bin
    cp -vr ./cpctl $out/libexec/cpctl/cpctl
    cp -vr ./.cpctl.yaml $out/share/cloud-playground/.cpctl.yaml
    cp -vr ./aws-local $out/share/cloud-playground/aws-local
    cp -vr ./kind $out/share/cloud-playground/kind
    cp -vr ./localstack $out/share/cloud-playground/localstack
    cp -vr ./manifests $out/share/cloud-playground/manifests
    cp -vr ./moto $out/share/cloud-playground/moto
    cp -vr ./tofu $out/share/cloud-playground/tofu
    cat > $out/bin/cpctl <<'EOF'
    #!${stdenvNoCC.shell}
    self_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
    prefix="$(CDPATH= cd -- "$self_dir/.." && pwd)"
    export CPCTL_ROOT="$prefix/share/cloud-playground"
    exec "$prefix/libexec/cpctl/cpctl" "$@"
    EOF
    chmod +x $out/bin/cpctl
  '';

  meta = {
    description = "Cloud Playground CLI for AWS and Kubernetes";
    homepage = "https://github.com/afeldman/cloud-playground";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
